### ISSUE TITLE
Standup Session Code Review - Change Semantic Tags

### ISSUE THREAD

**Issue by joshuaoivie** [Kakalanp/Portfolio-Joaquin#3]
Hello Joaquin,

Great job with your project. The only suggestion of a change I'd like to see is that you use the section tags to group logically related elements and use the divs tag to create other elements inside your section rather than using nested section tags.

Warm Regards,
Josh.

**Comment by jpol01** [comment]
Hi, I don't see anything to add (@joshuaivie ) already did the main recommendation. 

Great job. :smile_cat:
