### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by HectorTorresE** [Kakalanp/Portfolio-Joaquin#8]
Congratulations 👏 on your project, you did very well 💯:

**Comment by fed1k** [comment]
* Little suggestion: It would be better if animation or transition will be applied to make website more attractive.

**Comment by jpol01** [comment]
Hi, I couldn't see anything to add, the project is working properly. Congratulations.!!

![Alt Text](https://media.giphy.com/media/YRuFixSNWFVcXaxpmX/giphy.gif)
